<?xml version="1.0" encoding="utf-8"?><Database Name="QL_QUANCAFE" Class="dbQLCFDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=laptop-a5ciml19;Initial Catalog=QL_QUANCAFE;Integrated Security=True;Encrypt=False" SettingsObjectName="QL_CF.Properties.Settings" SettingsPropertyName="QL_QUANCAFEConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BAN" Member="BANs">
    <Type Name="BAN">
      <Column Name="MABAN" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENBAN" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="THUOCTINH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="BAN_HOADONBANHANG" Member="HOADONBANHANGs" ThisKey="MABAN" OtherKey="MABAN" Type="HOADONBANHANG" />
    </Type>
  </Table>
  <Table Name="dbo.CALAMVIEC" Member="CALAMVIECs">
    <Type Name="CALAMVIEC">
      <Column Name="MACLV" Type="System.String" DbType="Char(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENCLA" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GIOBD" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="GIOKT" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="SOTIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CALAMVIEC_CHITIETLUONGNHANVIEN" Member="CHITIETLUONGNHANVIENs" ThisKey="MACLV" OtherKey="MACLV" Type="CHITIETLUONGNHANVIEN" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETLUONGNHANVIEN" Member="CHITIETLUONGNHANVIENs">
    <Type Name="CHITIETLUONGNHANVIEN">
      <Column Name="MACLV" Type="System.String" DbType="Char(50) NOT NULL" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="TONGSOCALAMTRONGTHANG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LUONGTRONGTHANG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CALAMVIEC_CHITIETLUONGNHANVIEN" Member="CALAMVIEC" ThisKey="MACLV" OtherKey="MACLV" Type="CALAMVIEC" IsForeignKey="true" />
      <Association Name="NHANVIEN_CHITIETLUONGNHANVIEN" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETNHAPHANG" Member="CHITIETNHAPHANGs">
    <Type Name="CHITIETNHAPHANG">
      <Column Name="MANL" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="MAHDNH" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="THANHTIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HOADONNHAPHANG_CHITIETNHAPHANG" Member="HOADONNHAPHANG" ThisKey="MAHDNH" OtherKey="MAHDNH" Type="HOADONNHAPHANG" IsForeignKey="true" />
      <Association Name="NGUYENLIEU_CHITIETNHAPHANG" Member="NGUYENLIEU" ThisKey="MANL" OtherKey="MANL" Type="NGUYENLIEU" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOADONBANHANG" Member="HOADONBANHANGs">
    <Type Name="HOADONBANHANG">
      <Column Name="MAHDBH" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="MABAN" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="NGAYHD" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TONGTIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GIAMGIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HOADONBANHANG_CHITIETBANHANG" Member="CHITIETBANHANGs" ThisKey="MAHDBH" OtherKey="MAHDBH" Type="CHITIETBANHANG" />
      <Association Name="BAN_HOADONBANHANG" Member="BAN" ThisKey="MABAN" OtherKey="MABAN" Type="BAN" IsForeignKey="true" />
      <Association Name="NHANVIEN_HOADONBANHANG" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOADONNHAPHANG" Member="HOADONNHAPHANGs">
    <Type Name="HOADONNHAPHANG">
      <Column Name="MAHDNH" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="NGAYHBNH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="HOADONNHAPHANG_CHITIETNHAPHANG" Member="CHITIETNHAPHANGs" ThisKey="MAHDNH" OtherKey="MAHDNH" Type="CHITIETNHAPHANG" />
      <Association Name="NHANVIEN_HOADONNHAPHANG" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIHANG" Member="LOAIHANGs">
    <Type Name="LOAIHANG">
      <Column Name="MALH" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENLH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MOTA" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="LOAIHANG_NGUYENLIEU" Member="NGUYENLIEUs" ThisKey="MALH" OtherKey="MALH" Type="NGUYENLIEU" />
    </Type>
  </Table>
  <Table Name="dbo.NGUYENLIEU" Member="NGUYENLIEUs">
    <Type Name="NGUYENLIEU">
      <Column Name="MANL" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MANCC" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MALH" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="GIATIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NGUYENLIEU_CHITIETNHAPHANG" Member="CHITIETNHAPHANGs" ThisKey="MANL" OtherKey="MANL" Type="CHITIETNHAPHANG" />
      <Association Name="NGUYENLIEU_KHO" Member="KHOs" ThisKey="MANL" OtherKey="MANL" Type="KHO" />
      <Association Name="LOAIHANG_NGUYENLIEU" Member="LOAIHANG" ThisKey="MALH" OtherKey="MALH" Type="LOAIHANG" IsForeignKey="true" />
      <Association Name="NHACUNGCAP_NGUYENLIEU" Member="NHACUNGCAP" ThisKey="MANCC" OtherKey="MANCC" Type="NHACUNGCAP" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHACUNGCAP" Member="NHACUNGCAPs">
    <Type Name="NHACUNGCAP">
      <Column Name="MANCC" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNCC" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="NHACUNGCAP_NGUYENLIEU" Member="NGUYENLIEUs" ThisKey="MANCC" OtherKey="MANCC" Type="NGUYENLIEU" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MANV" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNV" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="CHUCVU" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NGAYVAOLAM" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="MATKHAU" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Association Name="NHANVIEN_CHITIETLUONGNHANVIEN" Member="CHITIETLUONGNHANVIENs" ThisKey="MANV" OtherKey="MANV" Type="CHITIETLUONGNHANVIEN" />
      <Association Name="NHANVIEN_HOADONBANHANG" Member="HOADONBANHANGs" ThisKey="MANV" OtherKey="MANV" Type="HOADONBANHANG" />
      <Association Name="NHANVIEN_HOADONNHAPHANG" Member="HOADONNHAPHANGs" ThisKey="MANV" OtherKey="MANV" Type="HOADONNHAPHANG" />
    </Type>
  </Table>
  <Table Name="dbo.Thongke" Member="Thongkes">
    <Type Name="Thongke">
      <Column Name="YEAR" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MONTH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TONGDOANHTHU" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThongkeNam" Member="ThongkeNams">
    <Type Name="ThongkeNam">
      <Column Name="Nam" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TONGDOANHTHU" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETBANHANG" Member="CHITIETBANHANGs">
    <Type Name="CHITIETBANHANG">
      <Column Name="MAHDBH" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="MAHH" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="HOADONBANHANG_CHITIETBANHANG" Member="HOADONBANHANG" ThisKey="MAHDBH" OtherKey="MAHDBH" Type="HOADONBANHANG" IsForeignKey="true" />
      <Association Name="KHO_CHITIETBANHANG" Member="KHO" ThisKey="MAHH" OtherKey="MAHH" Type="KHO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHO" Member="KHOs">
    <Type Name="KHO">
      <Column Name="MAHH" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANL" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="TENHH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GIASP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SOLUONGTON" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="KHO_CHITIETBANHANG" Member="CHITIETBANHANGs" ThisKey="MAHH" OtherKey="MAHH" Type="CHITIETBANHANG" />
      <Association Name="NGUYENLIEU_KHO" Member="NGUYENLIEU" ThisKey="MANL" OtherKey="MANL" Type="NGUYENLIEU" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.INHOADON" Member="INHOADONs">
    <Type Name="INHOADON">
      <Column Name="MAHDBH" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="NGAYHD" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TENBAN" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TENHH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GIASP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="THANHTIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TONGTIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.CapNhatGiaSanPham" Method="CapNhatGiaSanPham">
    <Parameter Name="MaHangHoa" Parameter="maHangHoa" Type="System.String" DbType="Char(10)" />
    <Parameter Name="GiaMoi" Parameter="giaMoi" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CNTHONGTINNHANVIEN" Method="CNTHONGTINNHANVIEN">
    <Parameter Name="MANV" Parameter="mANV" Type="System.String" DbType="Char(10)" />
    <Parameter Name="DIACHI" Parameter="dIACHI" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="SDT" Parameter="sDT" Type="System.String" DbType="NVarChar(15)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.TANGGIANUOC" Method="TANGGIANUOC">
    <Parameter Name="TENHH" Parameter="tENHH" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="TANG" Parameter="tANG" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XEMHDKH" Method="XEMHDKH">
    <Parameter Name="MAKH" Parameter="mAKH" Type="System.String" DbType="Char(10)" />
    <ElementType Name="XEMHDKHResult">
      <Column Name="MAHDBH" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="MABAN" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MAKH" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="NGAYHD" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TONGTIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GIAMGIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DOANHTHUHH" Method="DOANHTHUHH" IsComposable="true">
    <Parameter Name="THANG" Parameter="tHANG" Type="System.Int32" DbType="Int" />
    <Parameter Name="NAM" Parameter="nAM" Type="System.Int32" DbType="Int" />
    <ElementType Name="DOANHTHUHHResult">
      <Column Name="MAHH" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="TENHH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[SỐ LƯỢNG BÁN]" Member="SỐ_LƯỢNG_BÁN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GIASP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GIAMGIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[DOANH THU]" Member="DOANH_THU" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DOANHTHUNVCAONHAT" Method="DOANHTHUNVCAONHAT" IsComposable="true">
    <Parameter Name="THANG" Parameter="tHANG" Type="System.Int32" DbType="Int" />
    <Parameter Name="NAM" Parameter="nAM" Type="System.Int32" DbType="Int" />
    <ElementType Name="DOANHTHUNVCAONHATResult">
      <Column Name="MANV" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="TENNV" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CHUCVU" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[DOANH THU]" Member="DOANH_THU" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DSMATHANG" Method="DSMATHANG" IsComposable="true">
    <Parameter Name="MANCC" Parameter="mANCC" Type="System.String" DbType="Char(10)" />
    <ElementType Name="DSMATHANGResult">
      <Column Name="MANL" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="TENNL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.MatHangBanChayNhat" Method="MatHangBanChayNhat" IsComposable="true">
    <Parameter Name="Thang" Parameter="thang" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nam" Parameter="nam" Type="System.Int32" DbType="Int" />
    <ElementType Name="MatHangBanChayNhatResult">
      <Column Name="MAHH" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="TENHH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TongSoLuongBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.THONGTINKHACHHANGTUHOADON" Method="THONGTINKHACHHANGTUHOADON" IsComposable="true">
    <Parameter Name="MAHDBH" Parameter="mAHDBH" Type="System.String" DbType="Char(50)" />
    <ElementType Name="THONGTINKHACHHANGTUHOADONResult">
      <Column Name="TENKH" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="LOAIKHACHHANG" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.TIENLUONG" Method="TIENLUONG" IsComposable="true">
    <Parameter Name="MANV" Parameter="mANV" Type="System.String" DbType="Char(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.TinhSoLuongBanRaTheoMatHang" Method="TinhSoLuongBanRaTheoMatHang" IsComposable="true">
    <Parameter Name="Thang" Parameter="thang" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nam" Parameter="nam" Type="System.Int32" DbType="Int" />
    <ElementType Name="TinhSoLuongBanRaTheoMatHangResult">
      <Column Name="MAHH" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="TENHH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TongSoLuongBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TinhSoNgayLamViec" Method="TinhSoNgayLamViec" IsComposable="true">
    <Parameter Name="MANV" Parameter="mANV" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.TinhTongTienKhachHang" Method="TinhTongTienKhachHang" IsComposable="true">
    <Parameter Name="MAKH" Parameter="mAKH" Type="System.String" DbType="Char(10)" />
    <Return Type="System.Decimal" />
  </Function>
  <Function Name="dbo.CapNhatThongTinKh" Method="CapNhatThongTinKh">
    <Parameter Name="MAKH" Parameter="mAKH" Type="System.String" DbType="Char(10)" />
    <Parameter Name="TENKH" Parameter="tENKH" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="SDTMOI" Parameter="sDTMOI" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XUATTHONGTINKHCR" Method="XUATTHONGTINKHCR">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XUATSOLGBANRA" Method="XUATSOLGBANRA">
    <Parameter Name="THANG" Parameter="tHANG" Type="System.Int32" DbType="Int" />
    <Parameter Name="NAM" Parameter="nAM" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.TINHTONGLUONGNVTHEOCA" Method="TINHTONGLUONGNVTHEOCA">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CAPNHATTHONGTINLUONG" Method="CAPNHATTHONGTINLUONG">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XUATSOLGBANRA" Method="XUATSOLGBANRA1">
    <Parameter Name="THANG" Parameter="tHANG" Type="System.Int32" DbType="Int" />
    <Parameter Name="NAM" Parameter="nAM" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.TTDONHANG" Method="TTDONHANG">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.THEMKHACHHANG" Method="THEMKHACHHANG">
    <Parameter Name="MAKH" Parameter="mAKH" Type="System.String" DbType="Char(10)" />
    <Parameter Name="MALKH" Parameter="mALKH" Type="System.String" DbType="Char(10)" />
    <Parameter Name="TENKH" Parameter="tENKH" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="DIACHI" Parameter="dIACHI" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="SDT" Parameter="sDT" Type="System.String" DbType="Char(15)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XoaChiTietBanHang" Method="XoaChiTietBanHang">
    <Parameter Name="MAHDBH" Parameter="mAHDBH" Type="System.String" DbType="Char(10)" />
    <Parameter Name="MAHH" Parameter="mAHH" Type="System.String" DbType="Char(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XoaChiTietNhapHang" Method="XoaChiTietNhapHang">
    <Parameter Name="MANL" Parameter="mANL" Type="System.String" DbType="Char(10)" />
    <Parameter Name="MAHDNH" Parameter="mAHDNH" Type="System.String" DbType="Char(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XoaHoaDonBanHang" Method="XoaHoaDonBanHang">
    <Parameter Name="MAHDBH" Parameter="mAHDBH" Type="System.String" DbType="Char(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XoaHoaDonNhapHang" Method="XoaHoaDonNhapHang">
    <Parameter Name="MAHDNH" Parameter="mAHDNH" Type="System.String" DbType="Char(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XOAKHACHHANG" Method="XOAKHACHHANG">
    <Parameter Name="MAKH" Parameter="mAKH" Type="System.String" DbType="Char(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XOANHANVIEN" Method="XOANHANVIEN">
    <Parameter Name="MANV" Parameter="mANV" Type="System.String" DbType="Char(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SUANHANVIEN" Method="SUANHANVIEN">
    <Parameter Name="MANV" Parameter="mANV" Type="System.String" DbType="Char(10)" />
    <Parameter Name="TENNV" Parameter="tENNV" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="GIOITINH" Parameter="gIOITINH" Type="System.String" DbType="NVarChar(5)" />
    <Parameter Name="CHUCVU" Parameter="cHUCVU" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="NGAYVAOLAM" Parameter="nGAYVAOLAM" Type="System.DateTime" DbType="Date" />
    <Parameter Name="DIACHI" Parameter="dIACHI" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="SDT" Parameter="sDT" Type="System.String" DbType="Char(15)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SUAKHACHHANG" Method="SUAKHACHHANG">
    <Parameter Name="MAKH" Parameter="mAKH" Type="System.String" DbType="Char(10)" />
    <Parameter Name="MALKH" Parameter="mALKH" Type="System.String" DbType="Char(10)" />
    <Parameter Name="TENKH" Parameter="tENKH" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="DIACHI" Parameter="dIACHI" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="SDT" Parameter="sDT" Type="System.String" DbType="Char(15)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SuaHoaDonNhapHang" Method="SuaHoaDonNhapHang">
    <Parameter Name="MAHDNH" Parameter="mAHDNH" Type="System.String" DbType="Char(10)" />
    <Parameter Name="MANV" Parameter="mANV" Type="System.String" DbType="Char(10)" />
    <Parameter Name="NGAYHBNH" Parameter="nGAYHBNH" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SuaHoaDonBanHang" Method="SuaHoaDonBanHang">
    <Parameter Name="MAHDBH" Parameter="mAHDBH" Type="System.String" DbType="Char(10)" />
    <Parameter Name="MANV" Parameter="mANV" Type="System.String" DbType="Char(10)" />
    <Parameter Name="MABAN" Parameter="mABAN" Type="System.String" DbType="Char(10)" />
    <Parameter Name="MAKH" Parameter="mAKH" Type="System.String" DbType="Char(10)" />
    <Parameter Name="NGAYHD" Parameter="nGAYHD" Type="System.DateTime" DbType="Date" />
    <Parameter Name="TONGTIEN" Parameter="tONGTIEN" Type="System.Int32" DbType="Int" />
    <Parameter Name="GIAMGIA" Parameter="gIAMGIA" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SuaChiTietNhapHang" Method="SuaChiTietNhapHang">
    <Parameter Name="MANL" Parameter="mANL" Type="System.String" DbType="Char(10)" />
    <Parameter Name="MAHDNH" Parameter="mAHDNH" Type="System.String" DbType="Char(10)" />
    <Parameter Name="SOLUONG" Parameter="sOLUONG" Type="System.Int32" DbType="Int" />
    <Parameter Name="THANHTIEN" Parameter="tHANHTIEN" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SuaChiTietBanHang" Method="SuaChiTietBanHang">
    <Parameter Name="MAHDBH" Parameter="mAHDBH" Type="System.String" DbType="Char(10)" />
    <Parameter Name="MAHH" Parameter="mAHH" Type="System.String" DbType="Char(10)" />
    <Parameter Name="SOLUONG" Parameter="sOLUONG" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XOAMENU" Method="XOAMENU">
    <Parameter Name="MAHH" Parameter="mAHH" Type="System.String" DbType="Char(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.THEMCHITIETLUONG" Method="THEMCHITIETLUONG">
    <Parameter Name="MACLV" Parameter="mACLV" Type="System.String" DbType="Char(10)" />
    <Parameter Name="MANV" Parameter="mANV" Type="System.String" DbType="Char(10)" />
    <Parameter Name="SOCA" Parameter="sOCA" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XOACHITIETLUONG" Method="XOACHITIETLUONG">
    <Parameter Name="MACLV" Parameter="mACLV" Type="System.String" DbType="Char(10)" />
    <Parameter Name="MANV" Parameter="mANV" Type="System.String" DbType="Char(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.THEM1MENU" Method="THEM1MENU">
    <Parameter Name="MAHH" Parameter="mAHH" Type="System.String" DbType="Char(10)" />
    <Parameter Name="LH" Parameter="lH" Type="System.String" DbType="Char(10)" />
    <Parameter Name="TENHH" Parameter="tENHH" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="GIASP" Parameter="gIASP" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CheckUserRole" Method="CheckUserRole">
    <ElementType Name="CheckUserRoleResult">
      <Column Name="IsInRole" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ThemHoaDonNhapHang" Method="ThemHoaDonNhapHang">
    <Parameter Name="MAHDNH" Parameter="mAHDNH" Type="System.String" DbType="Char(10)" />
    <Parameter Name="MANV" Parameter="mANV" Type="System.String" DbType="Char(10)" />
    <Parameter Name="NGAYHBNH" Parameter="nGAYHBNH" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ThemHoaDonBanHang" Method="ThemHoaDonBanHang">
    <Parameter Name="MAHDBH" Parameter="mAHDBH" Type="System.String" DbType="Char(10)" />
    <Parameter Name="MANV" Parameter="mANV" Type="System.String" DbType="Char(10)" />
    <Parameter Name="MABAN" Parameter="mABAN" Type="System.String" DbType="Char(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DOIBAN" Method="DOIBAN">
    <Parameter Name="MAHDBH" Parameter="mAHDBH" Type="System.String" DbType="Char(10)" />
    <Parameter Name="MABANCU" Parameter="mABANCU" Type="System.String" DbType="Char(10)" />
    <Parameter Name="MABANMOI" Parameter="mABANMOI" Type="System.String" DbType="Char(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.THEMBAN" Method="THEMBAN">
    <Parameter Name="MABAN" Parameter="mABAN" Type="System.String" DbType="Char(10)" />
    <Parameter Name="TENBAN" Parameter="tENBAN" Type="System.String" DbType="NVarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XOABAN" Method="XOABAN">
    <Parameter Name="MABAN" Parameter="mABAN" Type="System.String" DbType="Char(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CAPNHATBAN" Method="CAPNHATBAN">
    <Parameter Name="MABAN" Parameter="mABAN" Type="System.String" DbType="Char(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ThemChiTietNhapHang" Method="ThemChiTietNhapHang">
    <Parameter Name="MANL" Parameter="mANL" Type="System.String" DbType="Char(10)" />
    <Parameter Name="MAHDNH" Parameter="mAHDNH" Type="System.String" DbType="Char(10)" />
    <Parameter Name="SOLUONG" Parameter="sOLUONG" Type="System.Int32" DbType="Int" />
    <Parameter Name="THANHTIEN" Parameter="tHANHTIEN" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.THEMHH" Method="THEMHH">
    <Parameter Name="MAHH" Parameter="mAHH" Type="System.String" DbType="Char(10)" />
    <Parameter Name="MANL" Parameter="mANL" Type="System.String" DbType="Char(10)" />
    <Parameter Name="TENNL" Parameter="tENNL" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="MANCC" Parameter="mANCC" Type="System.String" DbType="Char(10)" />
    <Parameter Name="MALOAI" Parameter="mALOAI" Type="System.String" DbType="Char(10)" />
    <Parameter Name="GIANHAP" Parameter="gIANHAP" Type="System.Int32" DbType="Int" />
    <Parameter Name="GIABAN" Parameter="gIABAN" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ThemChiTietBanHang" Method="ThemChiTietBanHang">
    <Parameter Name="MAHDBH" Parameter="mAHDBH" Type="System.String" DbType="Char(10)" />
    <Parameter Name="MAHH" Parameter="mAHH" Type="System.String" DbType="Char(10)" />
    <Parameter Name="SOLUONG" Parameter="sOLUONG" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XOAHH" Method="XOAHH">
    <Parameter Name="MAHDBH" Parameter="mAHDBH" Type="System.String" DbType="Char(10)" />
    <Parameter Name="MAHH" Parameter="mAHH" Type="System.String" DbType="Char(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.THAYDOISL" Method="THAYDOISL">
    <Parameter Name="MAHDBH" Parameter="mAHDBH" Type="System.String" DbType="Char(10)" />
    <Parameter Name="MAHH" Parameter="mAHH" Type="System.String" DbType="Char(10)" />
    <Parameter Name="SOLUONG" Parameter="sOLUONG" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.THEM1NV" Method="THEM1NV">
    <Parameter Name="MANV" Parameter="mANV" Type="System.String" DbType="Char(10)" />
    <Parameter Name="TENNV" Parameter="tENNV" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="GIOITINH" Parameter="gIOITINH" Type="System.String" DbType="NVarChar(5)" />
    <Parameter Name="CHUCVU" Parameter="cHUCVU" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="NGAYVAOLAM" Parameter="nGAYVAOLAM" Type="System.DateTime" DbType="Date" />
    <Parameter Name="DIACHI" Parameter="dIACHI" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="SDT" Parameter="sDT" Type="System.String" DbType="Char(15)" />
    <Parameter Name="MATKHAU" Parameter="mATKHAU" Type="System.String" DbType="Char(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SAOLUU" Method="SAOLUU">
    <Parameter Name="DUONGDAN" Parameter="dUONGDAN" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
</Database>