#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_CF
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_QUANCAFE")]
	public partial class dbQLCFDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBAN(BAN instance);
    partial void UpdateBAN(BAN instance);
    partial void DeleteBAN(BAN instance);
    partial void InsertCALAMVIEC(CALAMVIEC instance);
    partial void UpdateCALAMVIEC(CALAMVIEC instance);
    partial void DeleteCALAMVIEC(CALAMVIEC instance);
    partial void InsertHOADONBANHANG(HOADONBANHANG instance);
    partial void UpdateHOADONBANHANG(HOADONBANHANG instance);
    partial void DeleteHOADONBANHANG(HOADONBANHANG instance);
    partial void InsertHOADONNHAPHANG(HOADONNHAPHANG instance);
    partial void UpdateHOADONNHAPHANG(HOADONNHAPHANG instance);
    partial void DeleteHOADONNHAPHANG(HOADONNHAPHANG instance);
    partial void InsertLOAIHANG(LOAIHANG instance);
    partial void UpdateLOAIHANG(LOAIHANG instance);
    partial void DeleteLOAIHANG(LOAIHANG instance);
    partial void InsertNGUYENLIEU(NGUYENLIEU instance);
    partial void UpdateNGUYENLIEU(NGUYENLIEU instance);
    partial void DeleteNGUYENLIEU(NGUYENLIEU instance);
    partial void InsertNHACUNGCAP(NHACUNGCAP instance);
    partial void UpdateNHACUNGCAP(NHACUNGCAP instance);
    partial void DeleteNHACUNGCAP(NHACUNGCAP instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    partial void InsertKHO(KHO instance);
    partial void UpdateKHO(KHO instance);
    partial void DeleteKHO(KHO instance);
    #endregion
		
		public dbQLCFDataContext() : 
				base(global::QL_CF.Properties.Settings.Default.QL_QUANCAFEConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLCFDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLCFDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLCFDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLCFDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BAN> BANs
		{
			get
			{
				return this.GetTable<BAN>();
			}
		}
		
		public System.Data.Linq.Table<CALAMVIEC> CALAMVIECs
		{
			get
			{
				return this.GetTable<CALAMVIEC>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETLUONGNHANVIEN> CHITIETLUONGNHANVIENs
		{
			get
			{
				return this.GetTable<CHITIETLUONGNHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETNHAPHANG> CHITIETNHAPHANGs
		{
			get
			{
				return this.GetTable<CHITIETNHAPHANG>();
			}
		}
		
		public System.Data.Linq.Table<HOADONBANHANG> HOADONBANHANGs
		{
			get
			{
				return this.GetTable<HOADONBANHANG>();
			}
		}
		
		public System.Data.Linq.Table<HOADONNHAPHANG> HOADONNHAPHANGs
		{
			get
			{
				return this.GetTable<HOADONNHAPHANG>();
			}
		}
		
		public System.Data.Linq.Table<LOAIHANG> LOAIHANGs
		{
			get
			{
				return this.GetTable<LOAIHANG>();
			}
		}
		
		public System.Data.Linq.Table<NGUYENLIEU> NGUYENLIEUs
		{
			get
			{
				return this.GetTable<NGUYENLIEU>();
			}
		}
		
		public System.Data.Linq.Table<NHACUNGCAP> NHACUNGCAPs
		{
			get
			{
				return this.GetTable<NHACUNGCAP>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<Thongke> Thongkes
		{
			get
			{
				return this.GetTable<Thongke>();
			}
		}
		
		public System.Data.Linq.Table<ThongkeNam> ThongkeNams
		{
			get
			{
				return this.GetTable<ThongkeNam>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETBANHANG> CHITIETBANHANGs
		{
			get
			{
				return this.GetTable<CHITIETBANHANG>();
			}
		}
		
		public System.Data.Linq.Table<KHO> KHOs
		{
			get
			{
				return this.GetTable<KHO>();
			}
		}
		
		public System.Data.Linq.Table<INHOADON> INHOADONs
		{
			get
			{
				return this.GetTable<INHOADON>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CapNhatGiaSanPham")]
		public int CapNhatGiaSanPham([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHangHoa", DbType="Char(10)")] string maHangHoa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GiaMoi", DbType="Decimal(18,2)")] System.Nullable<decimal> giaMoi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHangHoa, giaMoi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CNTHONGTINNHANVIEN")]
		public int CNTHONGTINNHANVIEN([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MANV", DbType="Char(10)")] string mANV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DIACHI", DbType="NVarChar(100)")] string dIACHI, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SDT", DbType="NVarChar(15)")] string sDT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mANV, dIACHI, sDT);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TANGGIANUOC")]
		public int TANGGIANUOC([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TENHH", DbType="NVarChar(50)")] string tENHH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TANG", DbType="Float")] System.Nullable<double> tANG)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tENHH, tANG);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.XEMHDKH")]
		public ISingleResult<XEMHDKHResult> XEMHDKH([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAKH", DbType="Char(10)")] string mAKH)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mAKH);
			return ((ISingleResult<XEMHDKHResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DOANHTHUHH", IsComposable=true)]
		public IQueryable<DOANHTHUHHResult> DOANHTHUHH([global::System.Data.Linq.Mapping.ParameterAttribute(Name="THANG", DbType="Int")] System.Nullable<int> tHANG, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NAM", DbType="Int")] System.Nullable<int> nAM)
		{
			return this.CreateMethodCallQuery<DOANHTHUHHResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tHANG, nAM);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DOANHTHUNVCAONHAT", IsComposable=true)]
		public IQueryable<DOANHTHUNVCAONHATResult> DOANHTHUNVCAONHAT([global::System.Data.Linq.Mapping.ParameterAttribute(Name="THANG", DbType="Int")] System.Nullable<int> tHANG, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NAM", DbType="Int")] System.Nullable<int> nAM)
		{
			return this.CreateMethodCallQuery<DOANHTHUNVCAONHATResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tHANG, nAM);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DSMATHANG", IsComposable=true)]
		public IQueryable<DSMATHANGResult> DSMATHANG([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MANCC", DbType="Char(10)")] string mANCC)
		{
			return this.CreateMethodCallQuery<DSMATHANGResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mANCC);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MatHangBanChayNhat", IsComposable=true)]
		public IQueryable<MatHangBanChayNhatResult> MatHangBanChayNhat([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Thang", DbType="Int")] System.Nullable<int> thang, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nam", DbType="Int")] System.Nullable<int> nam)
		{
			return this.CreateMethodCallQuery<MatHangBanChayNhatResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), thang, nam);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.THONGTINKHACHHANGTUHOADON", IsComposable=true)]
		public IQueryable<THONGTINKHACHHANGTUHOADONResult> THONGTINKHACHHANGTUHOADON([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAHDBH", DbType="Char(50)")] string mAHDBH)
		{
			return this.CreateMethodCallQuery<THONGTINKHACHHANGTUHOADONResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mAHDBH);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TIENLUONG", IsComposable=true)]
		public System.Nullable<int> TIENLUONG([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MANV", DbType="Char(10)")] string mANV)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mANV).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TinhSoLuongBanRaTheoMatHang", IsComposable=true)]
		public IQueryable<TinhSoLuongBanRaTheoMatHangResult> TinhSoLuongBanRaTheoMatHang([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Thang", DbType="Int")] System.Nullable<int> thang, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nam", DbType="Int")] System.Nullable<int> nam)
		{
			return this.CreateMethodCallQuery<TinhSoLuongBanRaTheoMatHangResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), thang, nam);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TinhSoNgayLamViec", IsComposable=true)]
		public System.Nullable<int> TinhSoNgayLamViec([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MANV", DbType="NVarChar(50)")] string mANV)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mANV).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TinhTongTienKhachHang", IsComposable=true)]
		public System.Nullable<decimal> TinhTongTienKhachHang([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAKH", DbType="Char(10)")] string mAKH)
		{
			return ((System.Nullable<decimal>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mAKH).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CapNhatThongTinKh")]
		public int CapNhatThongTinKh([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAKH", DbType="Char(10)")] string mAKH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TENKH", DbType="NVarChar(50)")] string tENKH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SDTMOI", DbType="Int")] System.Nullable<int> sDTMOI)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mAKH, tENKH, sDTMOI);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.XUATTHONGTINKHCR")]
		public int XUATTHONGTINKHCR()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.XUATSOLGBANRA")]
		public int XUATSOLGBANRA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="THANG", DbType="Int")] System.Nullable<int> tHANG, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NAM", DbType="Int")] System.Nullable<int> nAM)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tHANG, nAM);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TINHTONGLUONGNVTHEOCA")]
		public int TINHTONGLUONGNVTHEOCA()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CAPNHATTHONGTINLUONG")]
		public int CAPNHATTHONGTINLUONG()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.XUATSOLGBANRA")]
		public int XUATSOLGBANRA1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="THANG", DbType="Int")] System.Nullable<int> tHANG, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NAM", DbType="Int")] System.Nullable<int> nAM)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tHANG, nAM);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TTDONHANG")]
		public int TTDONHANG()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.THEMKHACHHANG")]
		public int THEMKHACHHANG([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAKH", DbType="Char(10)")] string mAKH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MALKH", DbType="Char(10)")] string mALKH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TENKH", DbType="NVarChar(100)")] string tENKH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DIACHI", DbType="NVarChar(100)")] string dIACHI, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SDT", DbType="Char(15)")] string sDT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mAKH, mALKH, tENKH, dIACHI, sDT);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.XoaChiTietBanHang")]
		public int XoaChiTietBanHang([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAHDBH", DbType="Char(10)")] string mAHDBH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAHH", DbType="Char(10)")] string mAHH)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mAHDBH, mAHH);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.XoaChiTietNhapHang")]
		public int XoaChiTietNhapHang([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MANL", DbType="Char(10)")] string mANL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAHDNH", DbType="Char(10)")] string mAHDNH)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mANL, mAHDNH);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.XoaHoaDonBanHang")]
		public int XoaHoaDonBanHang([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAHDBH", DbType="Char(10)")] string mAHDBH)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mAHDBH);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.XoaHoaDonNhapHang")]
		public int XoaHoaDonNhapHang([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAHDNH", DbType="Char(10)")] string mAHDNH)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mAHDNH);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.XOAKHACHHANG")]
		public int XOAKHACHHANG([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAKH", DbType="Char(10)")] string mAKH)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mAKH);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.XOANHANVIEN")]
		public int XOANHANVIEN([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MANV", DbType="Char(10)")] string mANV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mANV);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SUANHANVIEN")]
		public int SUANHANVIEN([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MANV", DbType="Char(10)")] string mANV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TENNV", DbType="NVarChar(100)")] string tENNV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GIOITINH", DbType="NVarChar(5)")] string gIOITINH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CHUCVU", DbType="NVarChar(30)")] string cHUCVU, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NGAYVAOLAM", DbType="Date")] System.Nullable<System.DateTime> nGAYVAOLAM, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DIACHI", DbType="NVarChar(100)")] string dIACHI, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SDT", DbType="Char(15)")] string sDT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mANV, tENNV, gIOITINH, cHUCVU, nGAYVAOLAM, dIACHI, sDT);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SUAKHACHHANG")]
		public int SUAKHACHHANG([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAKH", DbType="Char(10)")] string mAKH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MALKH", DbType="Char(10)")] string mALKH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TENKH", DbType="NVarChar(100)")] string tENKH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DIACHI", DbType="NVarChar(100)")] string dIACHI, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SDT", DbType="Char(15)")] string sDT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mAKH, mALKH, tENKH, dIACHI, sDT);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SuaHoaDonNhapHang")]
		public int SuaHoaDonNhapHang([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAHDNH", DbType="Char(10)")] string mAHDNH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MANV", DbType="Char(10)")] string mANV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NGAYHBNH", DbType="Date")] System.Nullable<System.DateTime> nGAYHBNH)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mAHDNH, mANV, nGAYHBNH);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SuaHoaDonBanHang")]
		public int SuaHoaDonBanHang([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAHDBH", DbType="Char(10)")] string mAHDBH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MANV", DbType="Char(10)")] string mANV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MABAN", DbType="Char(10)")] string mABAN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAKH", DbType="Char(10)")] string mAKH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NGAYHD", DbType="Date")] System.Nullable<System.DateTime> nGAYHD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TONGTIEN", DbType="Int")] System.Nullable<int> tONGTIEN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GIAMGIA", DbType="Int")] System.Nullable<int> gIAMGIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mAHDBH, mANV, mABAN, mAKH, nGAYHD, tONGTIEN, gIAMGIA);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SuaChiTietNhapHang")]
		public int SuaChiTietNhapHang([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MANL", DbType="Char(10)")] string mANL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAHDNH", DbType="Char(10)")] string mAHDNH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SOLUONG", DbType="Int")] System.Nullable<int> sOLUONG, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="THANHTIEN", DbType="Int")] System.Nullable<int> tHANHTIEN)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mANL, mAHDNH, sOLUONG, tHANHTIEN);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SuaChiTietBanHang")]
		public int SuaChiTietBanHang([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAHDBH", DbType="Char(10)")] string mAHDBH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAHH", DbType="Char(10)")] string mAHH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SOLUONG", DbType="Int")] System.Nullable<int> sOLUONG)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mAHDBH, mAHH, sOLUONG);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.XOAMENU")]
		public int XOAMENU([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAHH", DbType="Char(10)")] string mAHH)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mAHH);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.THEMCHITIETLUONG")]
		public int THEMCHITIETLUONG([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MACLV", DbType="Char(10)")] string mACLV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MANV", DbType="Char(10)")] string mANV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SOCA", DbType="Int")] System.Nullable<int> sOCA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mACLV, mANV, sOCA);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.XOACHITIETLUONG")]
		public int XOACHITIETLUONG([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MACLV", DbType="Char(10)")] string mACLV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MANV", DbType="Char(10)")] string mANV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mACLV, mANV);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.THEM1MENU")]
		public int THEM1MENU([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAHH", DbType="Char(10)")] string mAHH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LH", DbType="Char(10)")] string lH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TENHH", DbType="NVarChar(50)")] string tENHH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GIASP", DbType="Float")] System.Nullable<double> gIASP)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mAHH, lH, tENHH, gIASP);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CheckUserRole")]
		public ISingleResult<CheckUserRoleResult> CheckUserRole()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<CheckUserRoleResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ThemHoaDonNhapHang")]
		public int ThemHoaDonNhapHang([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAHDNH", DbType="Char(10)")] string mAHDNH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MANV", DbType="Char(10)")] string mANV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NGAYHBNH", DbType="Date")] System.Nullable<System.DateTime> nGAYHBNH)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mAHDNH, mANV, nGAYHBNH);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ThemHoaDonBanHang")]
		public int ThemHoaDonBanHang([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAHDBH", DbType="Char(10)")] string mAHDBH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MANV", DbType="Char(10)")] string mANV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MABAN", DbType="Char(10)")] string mABAN)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mAHDBH, mANV, mABAN);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DOIBAN")]
		public int DOIBAN([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAHDBH", DbType="Char(10)")] string mAHDBH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MABANCU", DbType="Char(10)")] string mABANCU, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MABANMOI", DbType="Char(10)")] string mABANMOI)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mAHDBH, mABANCU, mABANMOI);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.THEMBAN")]
		public int THEMBAN([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MABAN", DbType="Char(10)")] string mABAN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TENBAN", DbType="NVarChar(30)")] string tENBAN)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mABAN, tENBAN);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.XOABAN")]
		public int XOABAN([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MABAN", DbType="Char(10)")] string mABAN)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mABAN);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CAPNHATBAN")]
		public int CAPNHATBAN([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MABAN", DbType="Char(10)")] string mABAN)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mABAN);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ThemChiTietNhapHang")]
		public int ThemChiTietNhapHang([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MANL", DbType="Char(10)")] string mANL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAHDNH", DbType="Char(10)")] string mAHDNH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SOLUONG", DbType="Int")] System.Nullable<int> sOLUONG, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="THANHTIEN", DbType="Int")] System.Nullable<int> tHANHTIEN)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mANL, mAHDNH, sOLUONG, tHANHTIEN);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.THEMHH")]
		public int THEMHH([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAHH", DbType="Char(10)")] string mAHH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MANL", DbType="Char(10)")] string mANL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TENNL", DbType="NVarChar(30)")] string tENNL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MANCC", DbType="Char(10)")] string mANCC, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MALOAI", DbType="Char(10)")] string mALOAI, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GIANHAP", DbType="Int")] System.Nullable<int> gIANHAP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GIABAN", DbType="Int")] System.Nullable<int> gIABAN)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mAHH, mANL, tENNL, mANCC, mALOAI, gIANHAP, gIABAN);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ThemChiTietBanHang")]
		public int ThemChiTietBanHang([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAHDBH", DbType="Char(10)")] string mAHDBH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAHH", DbType="Char(10)")] string mAHH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SOLUONG", DbType="Int")] System.Nullable<int> sOLUONG)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mAHDBH, mAHH, sOLUONG);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.XOAHH")]
		public int XOAHH([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAHDBH", DbType="Char(10)")] string mAHDBH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAHH", DbType="Char(10)")] string mAHH)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mAHDBH, mAHH);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.THAYDOISL")]
		public int THAYDOISL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAHDBH", DbType="Char(10)")] string mAHDBH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAHH", DbType="Char(10)")] string mAHH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SOLUONG", DbType="Int")] System.Nullable<int> sOLUONG)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mAHDBH, mAHH, sOLUONG);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.THEM1NV")]
		public int THEM1NV([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MANV", DbType="Char(10)")] string mANV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TENNV", DbType="NVarChar(100)")] string tENNV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GIOITINH", DbType="NVarChar(5)")] string gIOITINH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CHUCVU", DbType="NVarChar(30)")] string cHUCVU, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NGAYVAOLAM", DbType="Date")] System.Nullable<System.DateTime> nGAYVAOLAM, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DIACHI", DbType="NVarChar(100)")] string dIACHI, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SDT", DbType="Char(15)")] string sDT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MATKHAU", DbType="Char(30)")] string mATKHAU)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mANV, tENNV, gIOITINH, cHUCVU, nGAYVAOLAM, dIACHI, sDT, mATKHAU);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SAOLUU")]
		public int SAOLUU([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DUONGDAN", DbType="NVarChar(100)")] string dUONGDAN)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dUONGDAN);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BAN")]
	public partial class BAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MABAN;
		
		private string _TENBAN;
		
		private string _THUOCTINH;
		
		private EntitySet<HOADONBANHANG> _HOADONBANHANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMABANChanging(string value);
    partial void OnMABANChanged();
    partial void OnTENBANChanging(string value);
    partial void OnTENBANChanged();
    partial void OnTHUOCTINHChanging(string value);
    partial void OnTHUOCTINHChanged();
    #endregion
		
		public BAN()
		{
			this._HOADONBANHANGs = new EntitySet<HOADONBANHANG>(new Action<HOADONBANHANG>(this.attach_HOADONBANHANGs), new Action<HOADONBANHANG>(this.detach_HOADONBANHANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MABAN", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MABAN
		{
			get
			{
				return this._MABAN;
			}
			set
			{
				if ((this._MABAN != value))
				{
					this.OnMABANChanging(value);
					this.SendPropertyChanging();
					this._MABAN = value;
					this.SendPropertyChanged("MABAN");
					this.OnMABANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENBAN", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TENBAN
		{
			get
			{
				return this._TENBAN;
			}
			set
			{
				if ((this._TENBAN != value))
				{
					this.OnTENBANChanging(value);
					this.SendPropertyChanging();
					this._TENBAN = value;
					this.SendPropertyChanged("TENBAN");
					this.OnTENBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THUOCTINH", DbType="NVarChar(50)")]
		public string THUOCTINH
		{
			get
			{
				return this._THUOCTINH;
			}
			set
			{
				if ((this._THUOCTINH != value))
				{
					this.OnTHUOCTINHChanging(value);
					this.SendPropertyChanging();
					this._THUOCTINH = value;
					this.SendPropertyChanged("THUOCTINH");
					this.OnTHUOCTINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BAN_HOADONBANHANG", Storage="_HOADONBANHANGs", ThisKey="MABAN", OtherKey="MABAN")]
		public EntitySet<HOADONBANHANG> HOADONBANHANGs
		{
			get
			{
				return this._HOADONBANHANGs;
			}
			set
			{
				this._HOADONBANHANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOADONBANHANGs(HOADONBANHANG entity)
		{
			this.SendPropertyChanging();
			entity.BAN = this;
		}
		
		private void detach_HOADONBANHANGs(HOADONBANHANG entity)
		{
			this.SendPropertyChanging();
			entity.BAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CALAMVIEC")]
	public partial class CALAMVIEC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MACLV;
		
		private string _TENCLA;
		
		private System.TimeSpan _GIOBD;
		
		private System.TimeSpan _GIOKT;
		
		private System.Nullable<int> _SOTIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMACLVChanging(string value);
    partial void OnMACLVChanged();
    partial void OnTENCLAChanging(string value);
    partial void OnTENCLAChanged();
    partial void OnGIOBDChanging(System.TimeSpan value);
    partial void OnGIOBDChanged();
    partial void OnGIOKTChanging(System.TimeSpan value);
    partial void OnGIOKTChanged();
    partial void OnSOTIENChanging(System.Nullable<int> value);
    partial void OnSOTIENChanged();
    #endregion
		
		public CALAMVIEC()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACLV", DbType="Char(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MACLV
		{
			get
			{
				return this._MACLV;
			}
			set
			{
				if ((this._MACLV != value))
				{
					this.OnMACLVChanging(value);
					this.SendPropertyChanging();
					this._MACLV = value;
					this.SendPropertyChanged("MACLV");
					this.OnMACLVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENCLA", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TENCLA
		{
			get
			{
				return this._TENCLA;
			}
			set
			{
				if ((this._TENCLA != value))
				{
					this.OnTENCLAChanging(value);
					this.SendPropertyChanging();
					this._TENCLA = value;
					this.SendPropertyChanged("TENCLA");
					this.OnTENCLAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOBD", DbType="Time NOT NULL")]
		public System.TimeSpan GIOBD
		{
			get
			{
				return this._GIOBD;
			}
			set
			{
				if ((this._GIOBD != value))
				{
					this.OnGIOBDChanging(value);
					this.SendPropertyChanging();
					this._GIOBD = value;
					this.SendPropertyChanged("GIOBD");
					this.OnGIOBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOKT", DbType="Time NOT NULL")]
		public System.TimeSpan GIOKT
		{
			get
			{
				return this._GIOKT;
			}
			set
			{
				if ((this._GIOKT != value))
				{
					this.OnGIOKTChanging(value);
					this.SendPropertyChanging();
					this._GIOKT = value;
					this.SendPropertyChanged("GIOKT");
					this.OnGIOKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOTIEN", DbType="Int")]
		public System.Nullable<int> SOTIEN
		{
			get
			{
				return this._SOTIEN;
			}
			set
			{
				if ((this._SOTIEN != value))
				{
					this.OnSOTIENChanging(value);
					this.SendPropertyChanging();
					this._SOTIEN = value;
					this.SendPropertyChanged("SOTIEN");
					this.OnSOTIENChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETLUONGNHANVIEN")]
	public partial class CHITIETLUONGNHANVIEN
	{
		
		private string _MACLV;
		
		private string _MANV;
		
		private System.Nullable<int> _TONGSOCALAMTRONGTHANG;
		
		private System.Nullable<int> _LUONGTRONGTHANG;
		
		public CHITIETLUONGNHANVIEN()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACLV", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string MACLV
		{
			get
			{
				return this._MACLV;
			}
			set
			{
				if ((this._MACLV != value))
				{
					this._MACLV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					this._MANV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGSOCALAMTRONGTHANG", DbType="Int")]
		public System.Nullable<int> TONGSOCALAMTRONGTHANG
		{
			get
			{
				return this._TONGSOCALAMTRONGTHANG;
			}
			set
			{
				if ((this._TONGSOCALAMTRONGTHANG != value))
				{
					this._TONGSOCALAMTRONGTHANG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUONGTRONGTHANG", DbType="Int")]
		public System.Nullable<int> LUONGTRONGTHANG
		{
			get
			{
				return this._LUONGTRONGTHANG;
			}
			set
			{
				if ((this._LUONGTRONGTHANG != value))
				{
					this._LUONGTRONGTHANG = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETNHAPHANG")]
	public partial class CHITIETNHAPHANG
	{
		
		private string _MANL;
		
		private string _MAHDNH;
		
		private System.Nullable<int> _SOLUONG;
		
		private System.Nullable<int> _THANHTIEN;
		
		public CHITIETNHAPHANG()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANL", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MANL
		{
			get
			{
				return this._MANL;
			}
			set
			{
				if ((this._MANL != value))
				{
					this._MANL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHDNH", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MAHDNH
		{
			get
			{
				return this._MAHDNH;
			}
			set
			{
				if ((this._MAHDNH != value))
				{
					this._MAHDNH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this._SOLUONG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANHTIEN", DbType="Int")]
		public System.Nullable<int> THANHTIEN
		{
			get
			{
				return this._THANHTIEN;
			}
			set
			{
				if ((this._THANHTIEN != value))
				{
					this._THANHTIEN = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOADONBANHANG")]
	public partial class HOADONBANHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAHDBH;
		
		private string _MANV;
		
		private string _MABAN;
		
		private System.Nullable<System.DateTime> _NGAYHD;
		
		private System.Nullable<int> _TONGTIEN;
		
		private System.Nullable<int> _GIAMGIA;
		
		private EntityRef<BAN> _BAN;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHDBHChanging(string value);
    partial void OnMAHDBHChanged();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnMABANChanging(string value);
    partial void OnMABANChanged();
    partial void OnNGAYHDChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYHDChanged();
    partial void OnTONGTIENChanging(System.Nullable<int> value);
    partial void OnTONGTIENChanged();
    partial void OnGIAMGIAChanging(System.Nullable<int> value);
    partial void OnGIAMGIAChanged();
    #endregion
		
		public HOADONBANHANG()
		{
			this._BAN = default(EntityRef<BAN>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHDBH", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAHDBH
		{
			get
			{
				return this._MAHDBH;
			}
			set
			{
				if ((this._MAHDBH != value))
				{
					this.OnMAHDBHChanging(value);
					this.SendPropertyChanging();
					this._MAHDBH = value;
					this.SendPropertyChanged("MAHDBH");
					this.OnMAHDBHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MABAN", DbType="Char(10)")]
		public string MABAN
		{
			get
			{
				return this._MABAN;
			}
			set
			{
				if ((this._MABAN != value))
				{
					if (this._BAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMABANChanging(value);
					this.SendPropertyChanging();
					this._MABAN = value;
					this.SendPropertyChanged("MABAN");
					this.OnMABANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYHD", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYHD
		{
			get
			{
				return this._NGAYHD;
			}
			set
			{
				if ((this._NGAYHD != value))
				{
					this.OnNGAYHDChanging(value);
					this.SendPropertyChanging();
					this._NGAYHD = value;
					this.SendPropertyChanged("NGAYHD");
					this.OnNGAYHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGTIEN", DbType="Int")]
		public System.Nullable<int> TONGTIEN
		{
			get
			{
				return this._TONGTIEN;
			}
			set
			{
				if ((this._TONGTIEN != value))
				{
					this.OnTONGTIENChanging(value);
					this.SendPropertyChanging();
					this._TONGTIEN = value;
					this.SendPropertyChanged("TONGTIEN");
					this.OnTONGTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIAMGIA", DbType="Int")]
		public System.Nullable<int> GIAMGIA
		{
			get
			{
				return this._GIAMGIA;
			}
			set
			{
				if ((this._GIAMGIA != value))
				{
					this.OnGIAMGIAChanging(value);
					this.SendPropertyChanging();
					this._GIAMGIA = value;
					this.SendPropertyChanged("GIAMGIA");
					this.OnGIAMGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BAN_HOADONBANHANG", Storage="_BAN", ThisKey="MABAN", OtherKey="MABAN", IsForeignKey=true)]
		public BAN BAN
		{
			get
			{
				return this._BAN.Entity;
			}
			set
			{
				BAN previousValue = this._BAN.Entity;
				if (((previousValue != value) 
							|| (this._BAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BAN.Entity = null;
						previousValue.HOADONBANHANGs.Remove(this);
					}
					this._BAN.Entity = value;
					if ((value != null))
					{
						value.HOADONBANHANGs.Add(this);
						this._MABAN = value.MABAN;
					}
					else
					{
						this._MABAN = default(string);
					}
					this.SendPropertyChanged("BAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_HOADONBANHANG", Storage="_NHANVIEN", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.HOADONBANHANGs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.HOADONBANHANGs.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOADONNHAPHANG")]
	public partial class HOADONNHAPHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAHDNH;
		
		private string _MANV;
		
		private System.Nullable<System.DateTime> _NGAYHBNH;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHDNHChanging(string value);
    partial void OnMAHDNHChanged();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnNGAYHBNHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYHBNHChanged();
    #endregion
		
		public HOADONNHAPHANG()
		{
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHDNH", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAHDNH
		{
			get
			{
				return this._MAHDNH;
			}
			set
			{
				if ((this._MAHDNH != value))
				{
					this.OnMAHDNHChanging(value);
					this.SendPropertyChanging();
					this._MAHDNH = value;
					this.SendPropertyChanged("MAHDNH");
					this.OnMAHDNHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYHBNH", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYHBNH
		{
			get
			{
				return this._NGAYHBNH;
			}
			set
			{
				if ((this._NGAYHBNH != value))
				{
					this.OnNGAYHBNHChanging(value);
					this.SendPropertyChanging();
					this._NGAYHBNH = value;
					this.SendPropertyChanged("NGAYHBNH");
					this.OnNGAYHBNHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_HOADONNHAPHANG", Storage="_NHANVIEN", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.HOADONNHAPHANGs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.HOADONNHAPHANGs.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIHANG")]
	public partial class LOAIHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MALH;
		
		private string _TENLH;
		
		private string _MOTA;
		
		private EntitySet<NGUYENLIEU> _NGUYENLIEUs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMALHChanging(string value);
    partial void OnMALHChanged();
    partial void OnTENLHChanging(string value);
    partial void OnTENLHChanged();
    partial void OnMOTAChanging(string value);
    partial void OnMOTAChanged();
    #endregion
		
		public LOAIHANG()
		{
			this._NGUYENLIEUs = new EntitySet<NGUYENLIEU>(new Action<NGUYENLIEU>(this.attach_NGUYENLIEUs), new Action<NGUYENLIEU>(this.detach_NGUYENLIEUs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALH", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MALH
		{
			get
			{
				return this._MALH;
			}
			set
			{
				if ((this._MALH != value))
				{
					this.OnMALHChanging(value);
					this.SendPropertyChanging();
					this._MALH = value;
					this.SendPropertyChanged("MALH");
					this.OnMALHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TENLH
		{
			get
			{
				return this._TENLH;
			}
			set
			{
				if ((this._TENLH != value))
				{
					this.OnTENLHChanging(value);
					this.SendPropertyChanging();
					this._TENLH = value;
					this.SendPropertyChanged("TENLH");
					this.OnTENLHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTA", DbType="NVarChar(100)")]
		public string MOTA
		{
			get
			{
				return this._MOTA;
			}
			set
			{
				if ((this._MOTA != value))
				{
					this.OnMOTAChanging(value);
					this.SendPropertyChanging();
					this._MOTA = value;
					this.SendPropertyChanged("MOTA");
					this.OnMOTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIHANG_NGUYENLIEU", Storage="_NGUYENLIEUs", ThisKey="MALH", OtherKey="MALH")]
		public EntitySet<NGUYENLIEU> NGUYENLIEUs
		{
			get
			{
				return this._NGUYENLIEUs;
			}
			set
			{
				this._NGUYENLIEUs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NGUYENLIEUs(NGUYENLIEU entity)
		{
			this.SendPropertyChanging();
			entity.LOAIHANG = this;
		}
		
		private void detach_NGUYENLIEUs(NGUYENLIEU entity)
		{
			this.SendPropertyChanging();
			entity.LOAIHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NGUYENLIEU")]
	public partial class NGUYENLIEU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANL;
		
		private string _TENNL;
		
		private string _MANCC;
		
		private string _MALH;
		
		private System.Nullable<int> _GIATIEN;
		
		private EntitySet<KHO> _KHOs;
		
		private EntityRef<LOAIHANG> _LOAIHANG;
		
		private EntityRef<NHACUNGCAP> _NHACUNGCAP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANLChanging(string value);
    partial void OnMANLChanged();
    partial void OnTENNLChanging(string value);
    partial void OnTENNLChanged();
    partial void OnMANCCChanging(string value);
    partial void OnMANCCChanged();
    partial void OnMALHChanging(string value);
    partial void OnMALHChanged();
    partial void OnGIATIENChanging(System.Nullable<int> value);
    partial void OnGIATIENChanged();
    #endregion
		
		public NGUYENLIEU()
		{
			this._KHOs = new EntitySet<KHO>(new Action<KHO>(this.attach_KHOs), new Action<KHO>(this.detach_KHOs));
			this._LOAIHANG = default(EntityRef<LOAIHANG>);
			this._NHACUNGCAP = default(EntityRef<NHACUNGCAP>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANL", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANL
		{
			get
			{
				return this._MANL;
			}
			set
			{
				if ((this._MANL != value))
				{
					this.OnMANLChanging(value);
					this.SendPropertyChanging();
					this._MANL = value;
					this.SendPropertyChanged("MANL");
					this.OnMANLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNL", DbType="NVarChar(50)")]
		public string TENNL
		{
			get
			{
				return this._TENNL;
			}
			set
			{
				if ((this._TENNL != value))
				{
					this.OnTENNLChanging(value);
					this.SendPropertyChanging();
					this._TENNL = value;
					this.SendPropertyChanged("TENNL");
					this.OnTENNLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANCC", DbType="Char(10)")]
		public string MANCC
		{
			get
			{
				return this._MANCC;
			}
			set
			{
				if ((this._MANCC != value))
				{
					if (this._NHACUNGCAP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANCCChanging(value);
					this.SendPropertyChanging();
					this._MANCC = value;
					this.SendPropertyChanged("MANCC");
					this.OnMANCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALH", DbType="Char(10)")]
		public string MALH
		{
			get
			{
				return this._MALH;
			}
			set
			{
				if ((this._MALH != value))
				{
					if (this._LOAIHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALHChanging(value);
					this.SendPropertyChanging();
					this._MALH = value;
					this.SendPropertyChanged("MALH");
					this.OnMALHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIATIEN", DbType="Int")]
		public System.Nullable<int> GIATIEN
		{
			get
			{
				return this._GIATIEN;
			}
			set
			{
				if ((this._GIATIEN != value))
				{
					this.OnGIATIENChanging(value);
					this.SendPropertyChanging();
					this._GIATIEN = value;
					this.SendPropertyChanged("GIATIEN");
					this.OnGIATIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGUYENLIEU_KHO", Storage="_KHOs", ThisKey="MANL", OtherKey="MANL")]
		public EntitySet<KHO> KHOs
		{
			get
			{
				return this._KHOs;
			}
			set
			{
				this._KHOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIHANG_NGUYENLIEU", Storage="_LOAIHANG", ThisKey="MALH", OtherKey="MALH", IsForeignKey=true)]
		public LOAIHANG LOAIHANG
		{
			get
			{
				return this._LOAIHANG.Entity;
			}
			set
			{
				LOAIHANG previousValue = this._LOAIHANG.Entity;
				if (((previousValue != value) 
							|| (this._LOAIHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAIHANG.Entity = null;
						previousValue.NGUYENLIEUs.Remove(this);
					}
					this._LOAIHANG.Entity = value;
					if ((value != null))
					{
						value.NGUYENLIEUs.Add(this);
						this._MALH = value.MALH;
					}
					else
					{
						this._MALH = default(string);
					}
					this.SendPropertyChanged("LOAIHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHACUNGCAP_NGUYENLIEU", Storage="_NHACUNGCAP", ThisKey="MANCC", OtherKey="MANCC", IsForeignKey=true)]
		public NHACUNGCAP NHACUNGCAP
		{
			get
			{
				return this._NHACUNGCAP.Entity;
			}
			set
			{
				NHACUNGCAP previousValue = this._NHACUNGCAP.Entity;
				if (((previousValue != value) 
							|| (this._NHACUNGCAP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHACUNGCAP.Entity = null;
						previousValue.NGUYENLIEUs.Remove(this);
					}
					this._NHACUNGCAP.Entity = value;
					if ((value != null))
					{
						value.NGUYENLIEUs.Add(this);
						this._MANCC = value.MANCC;
					}
					else
					{
						this._MANCC = default(string);
					}
					this.SendPropertyChanged("NHACUNGCAP");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KHOs(KHO entity)
		{
			this.SendPropertyChanging();
			entity.NGUYENLIEU = this;
		}
		
		private void detach_KHOs(KHO entity)
		{
			this.SendPropertyChanging();
			entity.NGUYENLIEU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHACUNGCAP")]
	public partial class NHACUNGCAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANCC;
		
		private string _TENNCC;
		
		private string _DIACHI;
		
		private string _SDT;
		
		private EntitySet<NGUYENLIEU> _NGUYENLIEUs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANCCChanging(string value);
    partial void OnMANCCChanged();
    partial void OnTENNCCChanging(string value);
    partial void OnTENNCCChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    #endregion
		
		public NHACUNGCAP()
		{
			this._NGUYENLIEUs = new EntitySet<NGUYENLIEU>(new Action<NGUYENLIEU>(this.attach_NGUYENLIEUs), new Action<NGUYENLIEU>(this.detach_NGUYENLIEUs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANCC", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANCC
		{
			get
			{
				return this._MANCC;
			}
			set
			{
				if ((this._MANCC != value))
				{
					this.OnMANCCChanging(value);
					this.SendPropertyChanging();
					this._MANCC = value;
					this.SendPropertyChanged("MANCC");
					this.OnMANCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNCC", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TENNCC
		{
			get
			{
				return this._TENNCC;
			}
			set
			{
				if ((this._TENNCC != value))
				{
					this.OnTENNCCChanging(value);
					this.SendPropertyChanging();
					this._TENNCC = value;
					this.SendPropertyChanged("TENNCC");
					this.OnTENNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(50)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHACUNGCAP_NGUYENLIEU", Storage="_NGUYENLIEUs", ThisKey="MANCC", OtherKey="MANCC")]
		public EntitySet<NGUYENLIEU> NGUYENLIEUs
		{
			get
			{
				return this._NGUYENLIEUs;
			}
			set
			{
				this._NGUYENLIEUs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NGUYENLIEUs(NGUYENLIEU entity)
		{
			this.SendPropertyChanging();
			entity.NHACUNGCAP = this;
		}
		
		private void detach_NGUYENLIEUs(NGUYENLIEU entity)
		{
			this.SendPropertyChanging();
			entity.NHACUNGCAP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANV;
		
		private string _TENNV;
		
		private string _GIOITINH;
		
		private string _CHUCVU;
		
		private System.DateTime _NGAYVAOLAM;
		
		private string _DIACHI;
		
		private string _SDT;
		
		private string _MATKHAU;
		
		private EntitySet<HOADONBANHANG> _HOADONBANHANGs;
		
		private EntitySet<HOADONNHAPHANG> _HOADONNHAPHANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnTENNVChanging(string value);
    partial void OnTENNVChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnCHUCVUChanging(string value);
    partial void OnCHUCVUChanged();
    partial void OnNGAYVAOLAMChanging(System.DateTime value);
    partial void OnNGAYVAOLAMChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnMATKHAUChanging(string value);
    partial void OnMATKHAUChanged();
    #endregion
		
		public NHANVIEN()
		{
			this._HOADONBANHANGs = new EntitySet<HOADONBANHANG>(new Action<HOADONBANHANG>(this.attach_HOADONBANHANGs), new Action<HOADONBANHANG>(this.detach_HOADONBANHANGs));
			this._HOADONNHAPHANGs = new EntitySet<HOADONNHAPHANG>(new Action<HOADONNHAPHANG>(this.attach_HOADONNHAPHANGs), new Action<HOADONNHAPHANG>(this.detach_HOADONNHAPHANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNV", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TENNV
		{
			get
			{
				return this._TENNV;
			}
			set
			{
				if ((this._TENNV != value))
				{
					this.OnTENNVChanging(value);
					this.SendPropertyChanging();
					this._TENNV = value;
					this.SendPropertyChanged("TENNV");
					this.OnTENNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(5)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHUCVU", DbType="NVarChar(30)")]
		public string CHUCVU
		{
			get
			{
				return this._CHUCVU;
			}
			set
			{
				if ((this._CHUCVU != value))
				{
					this.OnCHUCVUChanging(value);
					this.SendPropertyChanging();
					this._CHUCVU = value;
					this.SendPropertyChanged("CHUCVU");
					this.OnCHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYVAOLAM", DbType="Date NOT NULL")]
		public System.DateTime NGAYVAOLAM
		{
			get
			{
				return this._NGAYVAOLAM;
			}
			set
			{
				if ((this._NGAYVAOLAM != value))
				{
					this.OnNGAYVAOLAMChanging(value);
					this.SendPropertyChanging();
					this._NGAYVAOLAM = value;
					this.SendPropertyChanged("NGAYVAOLAM");
					this.OnNGAYVAOLAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(100)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(15)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKHAU", DbType="Char(30)")]
		public string MATKHAU
		{
			get
			{
				return this._MATKHAU;
			}
			set
			{
				if ((this._MATKHAU != value))
				{
					this.OnMATKHAUChanging(value);
					this.SendPropertyChanging();
					this._MATKHAU = value;
					this.SendPropertyChanged("MATKHAU");
					this.OnMATKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_HOADONBANHANG", Storage="_HOADONBANHANGs", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<HOADONBANHANG> HOADONBANHANGs
		{
			get
			{
				return this._HOADONBANHANGs;
			}
			set
			{
				this._HOADONBANHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_HOADONNHAPHANG", Storage="_HOADONNHAPHANGs", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<HOADONNHAPHANG> HOADONNHAPHANGs
		{
			get
			{
				return this._HOADONNHAPHANGs;
			}
			set
			{
				this._HOADONNHAPHANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOADONBANHANGs(HOADONBANHANG entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_HOADONBANHANGs(HOADONBANHANG entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
		
		private void attach_HOADONNHAPHANGs(HOADONNHAPHANG entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_HOADONNHAPHANGs(HOADONNHAPHANG entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Thongke")]
	public partial class Thongke
	{
		
		private System.Nullable<int> _YEAR;
		
		private System.Nullable<int> _MONTH;
		
		private System.Nullable<int> _TONGDOANHTHU;
		
		public Thongke()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR", DbType="Int")]
		public System.Nullable<int> YEAR
		{
			get
			{
				return this._YEAR;
			}
			set
			{
				if ((this._YEAR != value))
				{
					this._YEAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONTH", DbType="Int")]
		public System.Nullable<int> MONTH
		{
			get
			{
				return this._MONTH;
			}
			set
			{
				if ((this._MONTH != value))
				{
					this._MONTH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGDOANHTHU", DbType="Int")]
		public System.Nullable<int> TONGDOANHTHU
		{
			get
			{
				return this._TONGDOANHTHU;
			}
			set
			{
				if ((this._TONGDOANHTHU != value))
				{
					this._TONGDOANHTHU = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThongkeNam")]
	public partial class ThongkeNam
	{
		
		private System.Nullable<int> _Nam;
		
		private System.Nullable<int> _TONGDOANHTHU;
		
		public ThongkeNam()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nam", DbType="Int")]
		public System.Nullable<int> Nam
		{
			get
			{
				return this._Nam;
			}
			set
			{
				if ((this._Nam != value))
				{
					this._Nam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGDOANHTHU", DbType="Int")]
		public System.Nullable<int> TONGDOANHTHU
		{
			get
			{
				return this._TONGDOANHTHU;
			}
			set
			{
				if ((this._TONGDOANHTHU != value))
				{
					this._TONGDOANHTHU = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETBANHANG")]
	public partial class CHITIETBANHANG
	{
		
		private string _MAHDBH;
		
		private string _MAHH;
		
		private int _SOLUONG;
		
		public CHITIETBANHANG()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHDBH", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MAHDBH
		{
			get
			{
				return this._MAHDBH;
			}
			set
			{
				if ((this._MAHDBH != value))
				{
					this._MAHDBH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHH", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MAHH
		{
			get
			{
				return this._MAHH;
			}
			set
			{
				if ((this._MAHH != value))
				{
					this._MAHH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int NOT NULL")]
		public int SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this._SOLUONG = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHO")]
	public partial class KHO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAHH;
		
		private string _MANL;
		
		private string _TENHH;
		
		private System.Nullable<int> _GIASP;
		
		private System.Nullable<int> _SOLUONGTON;
		
		private EntityRef<NGUYENLIEU> _NGUYENLIEU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHHChanging(string value);
    partial void OnMAHHChanged();
    partial void OnMANLChanging(string value);
    partial void OnMANLChanged();
    partial void OnTENHHChanging(string value);
    partial void OnTENHHChanged();
    partial void OnGIASPChanging(System.Nullable<int> value);
    partial void OnGIASPChanged();
    partial void OnSOLUONGTONChanging(System.Nullable<int> value);
    partial void OnSOLUONGTONChanged();
    #endregion
		
		public KHO()
		{
			this._NGUYENLIEU = default(EntityRef<NGUYENLIEU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHH", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAHH
		{
			get
			{
				return this._MAHH;
			}
			set
			{
				if ((this._MAHH != value))
				{
					this.OnMAHHChanging(value);
					this.SendPropertyChanging();
					this._MAHH = value;
					this.SendPropertyChanged("MAHH");
					this.OnMAHHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANL", DbType="Char(10)")]
		public string MANL
		{
			get
			{
				return this._MANL;
			}
			set
			{
				if ((this._MANL != value))
				{
					if (this._NGUYENLIEU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANLChanging(value);
					this.SendPropertyChanging();
					this._MANL = value;
					this.SendPropertyChanged("MANL");
					this.OnMANLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENHH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TENHH
		{
			get
			{
				return this._TENHH;
			}
			set
			{
				if ((this._TENHH != value))
				{
					this.OnTENHHChanging(value);
					this.SendPropertyChanging();
					this._TENHH = value;
					this.SendPropertyChanged("TENHH");
					this.OnTENHHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIASP", DbType="Int")]
		public System.Nullable<int> GIASP
		{
			get
			{
				return this._GIASP;
			}
			set
			{
				if ((this._GIASP != value))
				{
					this.OnGIASPChanging(value);
					this.SendPropertyChanging();
					this._GIASP = value;
					this.SendPropertyChanged("GIASP");
					this.OnGIASPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONGTON", DbType="Int")]
		public System.Nullable<int> SOLUONGTON
		{
			get
			{
				return this._SOLUONGTON;
			}
			set
			{
				if ((this._SOLUONGTON != value))
				{
					this.OnSOLUONGTONChanging(value);
					this.SendPropertyChanging();
					this._SOLUONGTON = value;
					this.SendPropertyChanged("SOLUONGTON");
					this.OnSOLUONGTONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGUYENLIEU_KHO", Storage="_NGUYENLIEU", ThisKey="MANL", OtherKey="MANL", IsForeignKey=true)]
		public NGUYENLIEU NGUYENLIEU
		{
			get
			{
				return this._NGUYENLIEU.Entity;
			}
			set
			{
				NGUYENLIEU previousValue = this._NGUYENLIEU.Entity;
				if (((previousValue != value) 
							|| (this._NGUYENLIEU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NGUYENLIEU.Entity = null;
						previousValue.KHOs.Remove(this);
					}
					this._NGUYENLIEU.Entity = value;
					if ((value != null))
					{
						value.KHOs.Add(this);
						this._MANL = value.MANL;
					}
					else
					{
						this._MANL = default(string);
					}
					this.SendPropertyChanged("NGUYENLIEU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.INHOADON")]
	public partial class INHOADON
	{
		
		private string _MAHDBH;
		
		private System.Nullable<System.DateTime> _NGAYHD;
		
		private string _TENBAN;
		
		private string _TENHH;
		
		private int _SOLUONG;
		
		private System.Nullable<int> _GIASP;
		
		private System.Nullable<int> _THANHTIEN;
		
		private System.Nullable<int> _TONGTIEN;
		
		public INHOADON()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHDBH", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MAHDBH
		{
			get
			{
				return this._MAHDBH;
			}
			set
			{
				if ((this._MAHDBH != value))
				{
					this._MAHDBH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYHD", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYHD
		{
			get
			{
				return this._NGAYHD;
			}
			set
			{
				if ((this._NGAYHD != value))
				{
					this._NGAYHD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENBAN", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TENBAN
		{
			get
			{
				return this._TENBAN;
			}
			set
			{
				if ((this._TENBAN != value))
				{
					this._TENBAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENHH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TENHH
		{
			get
			{
				return this._TENHH;
			}
			set
			{
				if ((this._TENHH != value))
				{
					this._TENHH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int NOT NULL")]
		public int SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this._SOLUONG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIASP", DbType="Int")]
		public System.Nullable<int> GIASP
		{
			get
			{
				return this._GIASP;
			}
			set
			{
				if ((this._GIASP != value))
				{
					this._GIASP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANHTIEN", DbType="Int")]
		public System.Nullable<int> THANHTIEN
		{
			get
			{
				return this._THANHTIEN;
			}
			set
			{
				if ((this._THANHTIEN != value))
				{
					this._THANHTIEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGTIEN", DbType="Int")]
		public System.Nullable<int> TONGTIEN
		{
			get
			{
				return this._TONGTIEN;
			}
			set
			{
				if ((this._TONGTIEN != value))
				{
					this._TONGTIEN = value;
				}
			}
		}
	}
	
	public partial class XEMHDKHResult
	{
		
		private string _MAHDBH;
		
		private string _MANV;
		
		private string _MABAN;
		
		private string _MAKH;
		
		private System.Nullable<System.DateTime> _NGAYHD;
		
		private System.Nullable<int> _TONGTIEN;
		
		private System.Nullable<int> _GIAMGIA;
		
		public XEMHDKHResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHDBH", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MAHDBH
		{
			get
			{
				return this._MAHDBH;
			}
			set
			{
				if ((this._MAHDBH != value))
				{
					this._MAHDBH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					this._MANV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MABAN", DbType="Char(10)")]
		public string MABAN
		{
			get
			{
				return this._MABAN;
			}
			set
			{
				if ((this._MABAN != value))
				{
					this._MABAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKH", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MAKH
		{
			get
			{
				return this._MAKH;
			}
			set
			{
				if ((this._MAKH != value))
				{
					this._MAKH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYHD", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYHD
		{
			get
			{
				return this._NGAYHD;
			}
			set
			{
				if ((this._NGAYHD != value))
				{
					this._NGAYHD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGTIEN", DbType="Int")]
		public System.Nullable<int> TONGTIEN
		{
			get
			{
				return this._TONGTIEN;
			}
			set
			{
				if ((this._TONGTIEN != value))
				{
					this._TONGTIEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIAMGIA", DbType="Int")]
		public System.Nullable<int> GIAMGIA
		{
			get
			{
				return this._GIAMGIA;
			}
			set
			{
				if ((this._GIAMGIA != value))
				{
					this._GIAMGIA = value;
				}
			}
		}
	}
	
	public partial class DOANHTHUHHResult
	{
		
		private string _MAHH;
		
		private string _TENHH;
		
		private System.Nullable<int> _SỐ_LƯỢNG_BÁN;
		
		private System.Nullable<int> _GIASP;
		
		private System.Nullable<int> _GIAMGIA;
		
		private System.Nullable<int> _DOANH_THU;
		
		public DOANHTHUHHResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHH", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MAHH
		{
			get
			{
				return this._MAHH;
			}
			set
			{
				if ((this._MAHH != value))
				{
					this._MAHH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENHH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TENHH
		{
			get
			{
				return this._TENHH;
			}
			set
			{
				if ((this._TENHH != value))
				{
					this._TENHH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SỐ LƯỢNG BÁN]", Storage="_SỐ_LƯỢNG_BÁN", DbType="Int")]
		public System.Nullable<int> SỐ_LƯỢNG_BÁN
		{
			get
			{
				return this._SỐ_LƯỢNG_BÁN;
			}
			set
			{
				if ((this._SỐ_LƯỢNG_BÁN != value))
				{
					this._SỐ_LƯỢNG_BÁN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIASP", DbType="Int")]
		public System.Nullable<int> GIASP
		{
			get
			{
				return this._GIASP;
			}
			set
			{
				if ((this._GIASP != value))
				{
					this._GIASP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIAMGIA", DbType="Int")]
		public System.Nullable<int> GIAMGIA
		{
			get
			{
				return this._GIAMGIA;
			}
			set
			{
				if ((this._GIAMGIA != value))
				{
					this._GIAMGIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DOANH THU]", Storage="_DOANH_THU", DbType="Int")]
		public System.Nullable<int> DOANH_THU
		{
			get
			{
				return this._DOANH_THU;
			}
			set
			{
				if ((this._DOANH_THU != value))
				{
					this._DOANH_THU = value;
				}
			}
		}
	}
	
	public partial class DOANHTHUNVCAONHATResult
	{
		
		private string _MANV;
		
		private string _TENNV;
		
		private string _CHUCVU;
		
		private System.Nullable<int> _DOANH_THU;
		
		public DOANHTHUNVCAONHATResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					this._MANV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNV", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TENNV
		{
			get
			{
				return this._TENNV;
			}
			set
			{
				if ((this._TENNV != value))
				{
					this._TENNV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHUCVU", DbType="NVarChar(30)")]
		public string CHUCVU
		{
			get
			{
				return this._CHUCVU;
			}
			set
			{
				if ((this._CHUCVU != value))
				{
					this._CHUCVU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DOANH THU]", Storage="_DOANH_THU", DbType="Int")]
		public System.Nullable<int> DOANH_THU
		{
			get
			{
				return this._DOANH_THU;
			}
			set
			{
				if ((this._DOANH_THU != value))
				{
					this._DOANH_THU = value;
				}
			}
		}
	}
	
	public partial class DSMATHANGResult
	{
		
		private string _MANL;
		
		private string _TENNL;
		
		private System.Nullable<int> _SOLUONG;
		
		public DSMATHANGResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANL", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MANL
		{
			get
			{
				return this._MANL;
			}
			set
			{
				if ((this._MANL != value))
				{
					this._MANL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNL", DbType="NVarChar(50)")]
		public string TENNL
		{
			get
			{
				return this._TENNL;
			}
			set
			{
				if ((this._TENNL != value))
				{
					this._TENNL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this._SOLUONG = value;
				}
			}
		}
	}
	
	public partial class MatHangBanChayNhatResult
	{
		
		private string _MAHH;
		
		private string _TENHH;
		
		private System.Nullable<int> _TongSoLuongBan;
		
		public MatHangBanChayNhatResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHH", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MAHH
		{
			get
			{
				return this._MAHH;
			}
			set
			{
				if ((this._MAHH != value))
				{
					this._MAHH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENHH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TENHH
		{
			get
			{
				return this._TENHH;
			}
			set
			{
				if ((this._TENHH != value))
				{
					this._TENHH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongSoLuongBan", DbType="Int")]
		public System.Nullable<int> TongSoLuongBan
		{
			get
			{
				return this._TongSoLuongBan;
			}
			set
			{
				if ((this._TongSoLuongBan != value))
				{
					this._TongSoLuongBan = value;
				}
			}
		}
	}
	
	public partial class THONGTINKHACHHANGTUHOADONResult
	{
		
		private string _TENKH;
		
		private string _DIACHI;
		
		private string _SDT;
		
		private string _LOAIKHACHHANG;
		
		public THONGTINKHACHHANGTUHOADONResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENKH", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TENKH
		{
			get
			{
				return this._TENKH;
			}
			set
			{
				if ((this._TENKH != value))
				{
					this._TENKH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(255)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this._DIACHI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(15)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this._SDT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAIKHACHHANG", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string LOAIKHACHHANG
		{
			get
			{
				return this._LOAIKHACHHANG;
			}
			set
			{
				if ((this._LOAIKHACHHANG != value))
				{
					this._LOAIKHACHHANG = value;
				}
			}
		}
	}
	
	public partial class TinhSoLuongBanRaTheoMatHangResult
	{
		
		private string _MAHH;
		
		private string _TENHH;
		
		private System.Nullable<int> _TongSoLuongBan;
		
		public TinhSoLuongBanRaTheoMatHangResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHH", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MAHH
		{
			get
			{
				return this._MAHH;
			}
			set
			{
				if ((this._MAHH != value))
				{
					this._MAHH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENHH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TENHH
		{
			get
			{
				return this._TENHH;
			}
			set
			{
				if ((this._TENHH != value))
				{
					this._TENHH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongSoLuongBan", DbType="Int")]
		public System.Nullable<int> TongSoLuongBan
		{
			get
			{
				return this._TongSoLuongBan;
			}
			set
			{
				if ((this._TongSoLuongBan != value))
				{
					this._TongSoLuongBan = value;
				}
			}
		}
	}
	
	public partial class CheckUserRoleResult
	{
		
		private string _IsInRole;
		
		public CheckUserRoleResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsInRole", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string IsInRole
		{
			get
			{
				return this._IsInRole;
			}
			set
			{
				if ((this._IsInRole != value))
				{
					this._IsInRole = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
